FROM n8nio/n8n:latest

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV WEBHOOK_URL=https://n8n-jbit-v1.onrender.com/

ENV N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
ENV N8N_ENABLE_REMOTE_WORKFLOW_CALLS=true
ENV N8N_BLOCK_ENV_ACCESS_IN_NODE=false

EXPOSE 5678

CMD ["n8n"]
